import mongoose,{Schema,model} from 'mongoose';
import mongooseAggregatePaginate from 'mongoose-aggregate-paginate-v2';
const videoSchema=new Schema({
    title:{
        type:String,
        required:true,
        trim:true,
        index:true
    },
    description:{
        type:String,
        required:true,
        trim:true,
    },
    thumbnail:{
        type:String,
        required:true
    },
     thumbnailPublicId:{
        type:String,
        required:true
     },
    videoFile:{
        type:String,
        required:true
    },
    videoFilePublicId:{
        type:String,
        required:true
    },
    views:{
        type:Number,
        default:0
    },
    owner:{
        type:Schema.Types.ObjectId,
        ref:"User",
    },
    duration:{
        type:Number,
        required:true
    },
    isPublished:{
        type:Boolean,
        default:true
    }
}
,{timestamps:true});
videoSchema.plugin(mongooseAggregatePaginate);
export const Video=model("Video",videoSchema)